module ocs2_ros2_msgs {
  module msg {
    @TypeCode(type="ocs2_ros2_msgs::msg::dds_::IndividualBenchmarks_")
    struct IndividualBenchmarks {
      string<255> description;
      sequence<double> values;
    };
  };
};
