module ocs2_ros2_msgs {
  module msg {

    @TypeCode(type="ocs2_ros2_msgs::msg::dds_::ModeSchedule_")
    struct ModeSchedule {
      sequence<double> event_times;

      sequence<long> mode_sequence;
    };
  };
};
