module ocs2_ros2_msgs {
  module msg {

    @TypeCode(type="ocs2_ros2_msgs::msg::dds_::Multiplier_")
    struct Multiplier {
      double time;
      double penalty;
      sequence<double> lagrangian;
    };
  };
};
